services:
  shoptrack-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: shoptrack-backend
    container_name: shoptrack-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
