services:
  shoptrack-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: shoptrack-backend
    container_name: shoptrack-backend
    env_file:
      - .env
    networks:
      - traefik_reverse_proxy_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.shoptrack-backend.entrypoints=websecure
      - traefik.http.routers.shoptrack-backend.rule=Host(`shoptrack-backend.${HOST_DOMAIN}`)
      - traefik.http.routers.shoptrack-backend.tls.certresolver=myresolver
      - traefik.http.services.shoptrack-backend.loadbalancer.server.port=8000
networks:
  traefik_reverse_proxy_network:
    external: true
