name: Test Backend

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/test-backend.yml'

jobs:
  test:
    name: Run backend tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: rye sync

      - name: Create .env file
        run: |
          cat << EOF > .env
          DJANGO_DEBUG=True
          DJANGO_SECRET_KEY=dummy-secret-key-for-github-actions-testing
          EOF

      - name: Run tests
        run: rye run test
